In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


importing the data


In [21]:
df = pd.read_csv('/content/Wine.csv')

In [22]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

splitting

In [23]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size= 0.2, random_state=0)

feature scaling

In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform (x_test)

Applying PCA

In [25]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 3)
x_train = pca.fit_transform(x_train)
x_test = pca.transform(x_test)

In [26]:
print(x_train)

[[-2.17884511e+00 -1.07218467e+00  7.25656631e-02]
 [-1.80819239e+00  1.57822344e+00  8.96476572e-03]
 [ 1.09829474e+00  2.22124345e+00 -1.09329403e-01]
 [-2.55584748e+00 -1.66210369e+00 -1.94662741e-01]
 [ 1.85698063e+00  2.41573166e-01 -1.00300685e+00]
 [ 2.58288576e+00 -1.37668170e+00 -1.47327363e+00]
 [ 8.72876119e-01  2.25618512e+00 -1.72526292e-01]
 [-4.18384029e-01  2.35415681e+00  1.48519692e+00]
 [-3.04977245e-01  2.27659433e+00 -1.06177089e+00]
 [ 2.14082532e+00 -1.10052871e+00  1.98193318e-01]
 [-2.98136465e+00 -2.47159183e-01  1.13626102e+00]
 [ 1.96188242e+00  1.25407738e+00 -4.17714193e-01]
 [-2.16177795e+00 -9.75966550e-01  1.46325283e+00]
 [ 2.21976084e+00 -2.39507167e+00 -8.20612727e-01]
 [-2.30179529e+00 -2.05791962e-01  8.02289900e-01]
 [-3.00953827e+00 -2.79141212e-01  9.33830035e-01]
 [ 2.63443473e+00 -8.68313119e-01  1.80166019e-01]
 [-1.09219965e+00 -3.53906625e+00 -1.28335128e+00]
 [ 2.62578435e+00 -2.96852840e-03  2.40918693e-01]
 [ 1.98077342e-01  2.29193443e+

In [27]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

LogisticRegression(random_state=0)

making the confusion metrics

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]


1.0